### ISSUE TITLE
SimpleIni fatal error

### ISSUE THREAD

**Issue by q1e123** [dezGusty/cpp-playground#2]
When I am trying to build the project I get:
```
fatal error: ConvertUTF.h: No such file or directory
```
from the [SimpleIni.h](https://github.com/dezGusty/cpp-playground/blob/master/thirdparty/simpleini/SimpleIni.h) file.

I think you also need to add [ConvertUTF.h](https://github.com/brofield/simpleini/blob/master/ConvertUTF.h) and [ConvertUTF.c](https://github.com/brofield/simpleini/blob/master/ConvertUTF.c) in the [simpleini folder](https://github.com/dezGusty/cpp-playground/tree/master/thirdparty/simpleini).

**Comment by dezGusty** [comment]
Should be fixed. Please try it out. I added the files from my phone and I hope I pasted the right stuff

**Comment by q1e123** [comment]
It seems good. Thanks!
