### ISSUE TITLE
matrix_console wrong expected value

### ISSUE THREAD

**Issue by q1e123** [dezGusty/cpp-playground#3]
In the [main_matrix_console.cpp](https://github.com/dezGusty/cpp-playground/blob/master/07_matrix_to_console/src/main_matrix_console.cpp) file the second and the third expected values are wrong since the index starts at 0 not 1 and it grows from the top to the bottom.
So for the second test the expected value should be:
```
X-----X----X-----XX-
--X-----------------
-----X--------------
--------X-----------
-----------X--------
--------------X-----
-----------------X--
-------------------X
------------------X-
-----------------X--
```
And for the third one:
```
X-----X----X-----XX-
--X-----------------
-----X--------------
-------OX-----------
-----------X--------
--------------X-----
-----------------X--
-------------------X
------------------X-
-----------------X--
```

**Comment by dezGusty** [comment]
No, as e-mailed and documented, first index is expected to be an X axis coordinate; second index Y axis.
"Atenție: puțin contrar modului obișnuit de lucru cu matrici, funcțiile cerute lucrează cu coordonate (x/y). "
