### ISSUE TITLE
22_sample_kitty_exe is not cross platform

### ISSUE THREAD

**Issue by q1e123** [dezGusty/cpp-playground#4]
The for each( in ) loop used in [main.cpp](https://github.com/dezGusty/cpp-playground/blob/master/22_sample_kitty_exe/src/main.cpp) is a Microsoft specific syntax that is not found in C++ standard.
To make it work on other operating systems you will need to use the C++ way of doing range based loop:

```
	for (Feline* feline : felines)
	{
		feline->make_sound();
	}

	// clean-up
	for (Feline* feline : felines)
	{
		delete feline;
	}
```

**Comment by dezGusty** [comment]
parcă țineam minte că nu era chiar ca în .NET, dar dacă s-a compilat... 😄 

Corectat 👍
